### PR TITLE
install.sh: Use /dev/tty for user input

### LINKED ISSUE #6291: Ubuntu 22.04 Install Issue(s)
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When running the install script (`sudo curl -o- https://raw.githubusercontent.com/Sonarr/Sonarr/develop/distribution/debian/install.sh | bash`) shown on the download page, the installation is not elevated unless the user becomes root `sudo -s`.
After doing this the script gets past the `echo "Please run as root."` but fails on checking the group

### Expected Behavior

The script should prompt for user and user group, then complete the install successfully.

### Steps To Reproduce

Have a relatively fresh install of ubuntu server 22.04 & attempt to run the install script.

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: v4 (Jan 2 2023)
- Docker Install: No
```

### What branch are you running?

Develop

### Trace Logs?

```
Running Sonarr Install Script - Version [1.0.1] as of [2023-12-29]
This will install [Sonarr] to [/opt/Sonarr] and use [/var/lib/sonarr/] for the AppData Directory
Sonarr will run as the user [app_uid=$(echo "$app_uid" | tr -d ' ')] and group [app_guid=$(echo "$app_guid" | tr -d ' ')]. By continuing, you've confirmed that that user and group will have READ and WRITE access to your Media Library and Download Client Completed Download directories
groupadd: 'app_guid=$(echo "$app_guid" | tr -d ' ')' is not a valid group name
```

### Anything else?

Running the commands manually seems to work

```
root@dlbox:/home/below9k# app_guid=$(echo "$app_guid" | tr -d ' ')
root@dlbox:/home/below9k# echo $app_guid

root@dlbox:/home/below9k# app_guid=${app_guid:-media}
root@dlbox:/home/below9k# echo $app_guid
media
root@dlbox:/home/below9k# groupadd "$app_guid"
groupadd: group 'media' already exists
root@dlbox:/home/below9k#
```

### PR DESCRIPTION
**Pull request by markus101**
#### Database Migration
NO

#### Description

Instead of changing how the script is downloaded we can read user input from `/dev/tty`.

Found this solution on https://unix.stackexchange.com/questions/121231/how-to-read-user-input-from-a-pipe and https://unix.stackexchange.com/questions/166853/how-to-read-user-input-when-using-script-in-pipe

#### Issues Fixed or Closed by this PR

* Closes #6291

### CODE REVIEW

**Review by stevietv — APPROVED** [review]

File: distribution/debian/install.sh [hunk 1]
```diff
@@ -14,7 +15,7 @@
 #OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 #WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 
-scriptversion="1.0.1"
+scriptversion="1.0.2"
 scriptdate="2023-12-29"
```
Comment (stevietv) [inline distribution/debian/install.sh:19]:
```suggestion
scriptdate="2024-01-03"
```

**Review by stevietv — CHANGES_REQUESTED** [review]
